### ISSUE TITLE
Just an FYI regarding System.DateTime formatting...

### ISSUE THREAD

**Issue by trossr32** [BanterBoy/ProfileFunctions#1]
Hey mate. Noticed that you're formatting datetimes into strings like this in your speedtest function:

`([datetime]::Today).ToShortDateString().replace("/", "-") + "-" + ([datetime]::Now).ToLongTimeString().replace(":", "-")`

Worth taking a quick look at all the formatting options for datetime [here](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings), as you can write the above as: 

`[datetime]::Now.ToString("dd-MM-yyyy-HH-mm-ss")`

Makes it more concise, easier to read and you don't have to cock about with replace statements 👍

**Comment by BanterBoy** [comment]
Thanks, I did not know that........Dates are always a twat to deal with

**Comment by trossr32** [comment]
They are mate, but once you can remember the characters required for formatting it's usually easier to just define the format string rather than using the predefined ToShortDateString(), etc methods
